server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://udemy-sever-db.cpaikgj1hrdi.ap-northeast-2.rds.amazonaws.com:3306/instagram_clone
    username: just
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # 최적화 옵션

loggin.level:
  org.hibernate.SQL: debug